codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        target: 70%
        threshold: 2
        base: auto
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default

ignore: 
  - "src/constant" 
  - "src/assets/domain.js"
  - "src/index.js"
  - "src/serviceWorker.js"
  - "src/setupTests.js"
  - "src/assets/fonts/Deliveroo_files" 

codecov:
  token: 8d30c046-b0c1-4c4d-935c-7ed21666e902
